name: Deployment

on:
  push:
    branches:
      - development

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com/Naveen-Maddimsetty/samplenode/
    steps:
      - name: deploy
        # ...deployment-specific steps
